#!/bin/bash

## Description: Start the Dev Server of the Sillage theme
## Usage: sillage:watch
## Example: "ddev sillage:watch "


if [ ! -d "/var/www/html/web/themes/custom/sillage" ]; then
    echo "Error: Theme 'sillage' not found in web/themes/custom/"
    exit 1
fi
cd /var/www/html/web/themes/custom/sillage || exit
npm run watch
