#!/bin/bash

## Description: Build the Sillage theme
## Usage: sillage:build
## Example: "ddev sillage:build"

if [ ! -d "/var/www/html/web/themes/custom/sillage" ]; then
    echo "Error: Theme 'sillage' not found in web/themes/custom/"
    exit 1
fi
cd /var/www/html/web/themes/custom/sillage || exit
npm run build
